Yet more TSDoc
coda/packs-sdk pull request #1538
Opened 2021-11-10 22:57 UTC by jonathan-codaio

This is basically all of the rest of the reachable entities. After this, I can send a followup to rework tsdoc_progress.ts as a unittest that enforces that all reachable entities have documentation.

This isn't quite the end of it though, all of the entities that typedoc is currently throwing warnings about will need to be exported and documented too. I'll work on those next.

PTAL @ekoleda-codaio @coda/packs

2021-11-12 14:50 UTC, ekoleda-codaio requested changes

2021-11-12 14:50 UTC, ekoleda-codaio commented on schema.ts
> +   * When true, indicates that an object return value for a formula that has this schema must
Does this just add build-time checks? What happens though at runtime if you don't return it?

2021-11-12 14:50 UTC, ekoleda-codaio commented on schema.ts
> + * You may optionally specify an {@link identity} when defining an object schema.
Some of these links aren't working correctly:

https://coda-packs-sdk--1538.com.readthedocs.build/en/1538/reference/sdk/interfaces/IdentityDefinition/

Should they have been prefixed with a type name?

2021-11-12 14:50 UTC, ekoleda-codaio commented on schema.ts
> +   * The dynamic URL, this is a schema for a dynamic sync table. When returning a schema from the {@link getSchema}
Are you missing an "if" here? ", if this is a ..."

2021-11-12 14:50 UTC, ekoleda-codaio commented on types.ts
> +   * with the creating user's Coda email address.
In my experience in the UI it's labeled with the user's username, not email address.

2021-11-12 22:24 UTC, jonathan-codaio commented
Mind if I merge this and make followups? I'm working on the final cleanup and trying to avoid major rebase conflicts before I get too far.

2021-11-12 23:37 UTC, ekoleda-codaio commented on schema.ts
> +   * When true, indicates that an object return value for a formula that has this schema must
The key question I'm getting at is "what happens if I screw up and it's empty?" It sounds like the references that rely on the field won't work, but in general your Pack won't blow up.

2021-11-12 23:38 UTC, ekoleda-codaio commented on schema.ts
> + * You may optionally specify an {@link identity} when defining an object schema.
Just checked the same preview link and those aren't working either.

2021-11-12 23:39 UTC, ekoleda-codaio commented
> Mind if I merge this and make followups? I'm working on the final cleanup and trying to avoid major rebase conflicts before I get too far.

Looks like the links are still broken, but once those are fixed feel free to merge.

2021-11-12 23:44 UTC, jonathan-codaio commented
> > Mind if I merge this and make followups? I'm working on the final cleanup and trying to avoid major rebase conflicts before I get too far.
> 
> Looks like the links are still broken, but once those are fixed feel free to merge.

Cool, will look into these, but mind approving so I can try to merge if you've already signed off for the night?

2021-11-13 00:33 UTC, jonathan-codaio commented
> > > Mind if I merge this and make followups? I'm working on the final cleanup and trying to avoid major rebase conflicts before I get too far.
> > 
> > 
> > Looks like the links are still broken, but once those are fixed feel free to merge.
> 
> Cool, will look into these, but mind approving so I can try to merge if you've already signed off for the night?

Ok these are fixed. Required adding more exports, which in turn required adding more tsdoc, which was pulling on the thread that I was trying to address in my follow-on PR to start dealing with typedoc warnings by adding new exports and entrypoints. Each new import brings in a bunch of new identifiers with it so fixing any single one of these can be deep rabbithole, now that we have doc comment enforcement turned on.

2021-11-13 00:34 UTC, patrick-codaio approved these changes

2021-11-13 00:43 UTC, merged