add entity id property
coda/packs-sdk pull request #3016
Opened 2024-07-02 19:30 UTC by gary-codaio

Goal of this is that for some sync tables, it may make sense for some rows to be grouped into entity ids, this property should capture that.

2024-07-02 20:25 UTC, patrick-codaio commented on schema.ts
> +   * an entityProperty, which uniquely identifies the entity that groups 1 to multiple rows.
Could you include an example, like a document being broken up into chunks?

2024-07-02 20:28 UTC, patrick-codaio approved these changes
LGTM, but can @ekoleda-codaio also approve the name? Slack context: https://codaproject.slack.com/archives/C06HG23CV08/p1718915995227269?thread_ts=1718906405.616409&cid=C06HG23CV08

2024-07-02 20:32 UTC, patrick-codaio commented
oh, also can you bump the prerelease version in package.json

2024-07-08 17:51 UTC, ekoleda-codaio commented
Sorry for the delay, I was OOO most of last week. I think `parentIdProperty` would make more sense. In the description you already write "represents a unique id for a parent entity for the object". The parent of a DocChunk would be a Doc, for example. I think `idProperty` and `entityIdProperty` would be very hard to distinguish in auto-complete.

2024-07-08 18:16 UTC, gary-codaio commented
@ekoleda-codaio thanks, good point. Renamed

2024-07-08 19:36 UTC, ekoleda-codaio requested changes

2024-07-08 19:36 UTC, ekoleda-codaio commented on schema.ts
> +   * parent entity for the object. It is recommended for sync table schemas with a bodyTextProperty to specify an
In theory, could you specify a `bodyTextProperty` without chunking it into multiple rows? If, perhaps clarify that here?

2024-07-08 19:36 UTC, ekoleda-codaio commented on schema.ts
> +   * document, while each row's id can be unique to the chunk.
Should probably mark with `@hidden`, to match the other new fields.

2024-07-09 15:06 UTC, ekoleda-codaio approved these changes

2024-07-09 16:57 UTC, merged